CREATE DATABASE KOMPANY ;
USE KOMPANY ;
CREATE TABLE EMPLOYEE(
   ID INT PRIMARY KEY,
   F_NAME VARCHAR(20),
   L_NAME VARCHAR(20),
   B_DATE DATE,
   SEX VARCHAR(1),
   SALARY INT,
   SUPER_ID INT,
   BRANCH_ID INT

);
CREATE TABLE BRANCH(
  BRANCH_ID INT PRIMARY KEY,
  B_NAME VARCHAR(20),
  MNG_ID INT,
  START_DATE DATE,
  FOREIGN KEY(MNG_ID) REFERENCES EMPLOYEE(ID) ON DELETE SET NULL
);
ALTER  TABLE  EMPLOYEE
ADD FOREIGN KEY(BRANCH_ID)
REFERENCES BRANCH(BRANCH_ID)
ON DELETE SET NULL; 
SELECT * FROM EMPLOYEE;
ALTER  TABLE  EMPLOYEE
ADD FOREIGN KEY(SUPER_ID)
REFERENCES EMPLOYEE(ID)
ON DELETE SET NULL;
CREATE TABLE CLIENTS(
  CLIENT_ID INT PRIMARY KEY,
  C_NAME VARCHAR(20),
  BRANCH_ID INT,
  FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE SET NULL
);
CREATE TABLE WORKS_WITH(
  ID INT,
  CLIENT_ID INT,
  TOTAL_SALES INT,
  FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE,
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID) ON DELETE CASCADE

);

INSERT INTO EMPLOYEE VALUES(100,'SOLO','WAIRE','1978-05-11','M',14000,NULL,NULL);
INSERT INTO EMPLOYEE VALUES(102,'JAMES','WAINE','1956-07-01','M',134000,NULL,NULL);
INSERT INTO EMPLOYEE VALUES(103,'ANN','KANANU','1989-02-19','F',100000,NULL,NULL);
INSERT INTO EMPLOYEE VALUES(116,'MARY','NYAKO','1987-11-18','F',22000,103,3);
INSERT INTO BRANCH VALUES(1,'CORPORATE',100,'2000-06-03');
INSERT INTO BRANCH VALUES(2,'UFUNDI',102,'2008-08-07');
INSERT INTO BRANCH VALUES(3,'FINANCE',103,'2008-06-23');
SELECT * FROM BRANCH;

UPDATE EMPLOYEE
SET BRANCH_ID =2
WHERE ID=103;

CREATE TABLE SUPPLIER(
  BRANCH_ID INT PRIMARY KEY,
  SUP_NAME VARCHAR(20) ,
  SUP_TYPE VARCHAR(20),
  FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE
  
 );
INSERT INTO WORKS_WITH VALUES(109,405,900000);

SELECT * FROM EMPLOYEE ORDER BY SALARY ;
SELECT F_NAME AS FORENAME FROM EMPLOYEE;
SELECT DISTINCT SEX FROM EMPLOYEE;

SELECT COUNT(ID) FROM EMPLOYEE;
SELECT COUNT(SUPER_ID) FROM EMPLOYEE;

--no of females born after 1980--;
SELECT COUNT(ID)FROM EMPLOYEE WHERE SEX='F' and B_DATE >'1980-01-01';

SELECT SUM(SALARY) FROM EMPLOYEE;
SELECT MAX(TOTAL_SALES) FROM WORKS_WITH;

SELECT SUM(TOTAL_SALES) FROM WORKS_WITH WHERE ID=106;

SELECT COUNT(SEX),SEX
FROM EMPLOYEE
GROUP BY (SEX);

SELECT SUM(TOTAL_SALES),ID
FROM WORKS_WITH
GROUP BY (ID);

